Repository UniMath/agda-unimath, pull requests merged in 2023-02, with the labels that each got.

#421 Update CI with latest Github Actions and other improvements
  .github/workflows/ci.yaml
  Makefile
Labels: CI, repo-maintenance

#424 Enhance CI
  .github/workflows/ci.yaml
  Makefile
Labels: enhancement, CI, repo-maintenance

#426 Deploy gh-pages using Github artifacts and action/deploy-pages
  .github/workflows/ci.yaml
Labels: CI, repo-maintenance

#427 use master cache in case there's no other
  .github/workflows/ci.yaml
  .github/workflows/pages.yaml
Labels: CI, repo-maintenance, website

#428 Fix Badge for website status and other minor typos
  .github/workflows/pages.yaml
  README.md
Labels: repo-maintenance

#447 Add missing references
  src/SUMMARY.lagda.md
  src/finite-group-theory.lagda.md
  src/foundation.lagda.md
  src/graph-theory.lagda.md
  src/structured-types.lagda.md
Labels: documentation
