Repository UniMath/agda-unimath, pull requests merged in 2023-06, with the labels that each got.

#645 Document how to build the website locally
  HOWTO-INSTALL.md
Labels: documentation, website

#646 fix broken link
  src/foundation-core/path-split-maps.lagda.md
Labels: fix

#653 complete refactoring of dependent identifications
  src/finite-group-theory/delooping-sign-homomorphism.lagda.md
  src/finite-group-theory/finite-type-groups.lagda.md
  src/foundation-core/dependent-identifications.lagda.md
  src/foundation-core/equality-dependent-pair-types.lagda.md
  src/foundation/action-on-identifications-dependent-functions.lagda.md
  src/foundation/dependent-identifications.lagda.md
  src/foundation/equality-dependent-pair-types.lagda.md
  src/foundation/transport.lagda.md
  src/group-theory/loop-groups-sets.lagda.md
Labels: cleanup, foundation

#656 Torsorial type families
  src/foundation-core/identity-types.lagda.md
  src/foundation-core/small-types.lagda.md
  src/foundation.lagda.md
  src/foundation/axiom-l.lagda.md
  src/foundation/identity-types.lagda.md
  src/foundation/pointed-torsorial-type-families.lagda.md
  src/foundation/sorial-type-families.lagda.md
  src/foundation/torsorial-type-families.lagda.md
  src/foundation/universal-property-identity-types.lagda.md
  src/synthetic-homotopy-theory.lagda.md
  src/synthetic-homotopy-theory/join-powers-of-types.lagda.md
Labels: foundation, synthetic-homotopy-theory

#511 Clarify conventions
  .github/workflows/ci.yaml
  .github/workflows/pages.yaml
  .pre-commit-config.yaml
  CITATION.cff
  CITE-THIS-LIBRARY.md
  CODINGSTYLE.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  DESIGN-PRINCIPLES.md
  FILE-CONVENTIONS.md
  GRANT-ACKNOWLEDGEMENTS.md
  HOME.md
  HOWTO-INSTALL.md
  Makefile
  README.md
  grant-acknowledgements.md
  scripts/even_indentation_conventions.py
  scripts/generate_main_index_file.py
  scripts/markdown_conventions.py
  scripts/requirements.txt
  scripts/spaces_conventions_simple.py
  src/synthetic-homotopy-theory/26-descent.lagda.md
  src/synthetic-homotopy-theory/26-id-pushout.lagda.md
  src/synthetic-homotopy-theory/27-sequences.lagda.md
  src/trees/directed-trees.lagda.md
  theme/js/custom.js
Labels: documentation, repo-maintenance

#669 Finite coverings in locales
  src/order-theory.lagda.md
  src/order-theory/coverings-locales.lagda.md
  src/order-theory/finite-coverings-locales.lagda.md
Labels: order-theory

#671 Whitespace after closing braces and before opening braces
  CONTRIBUTING.md
  scripts/spaces_conventions_simple.py
  src/commutative-algebra/sums-commutative-rings.lagda.md
  src/elementary-number-theory/fundamental-theorem-of-arithmetic.lagda.md
  src/elementary-number-theory/maximum-natural-numbers.lagda.md
  src/elementary-number-theory/natural-numbers.lagda.md
  src/elementary-number-theory/prime-numbers.lagda.md
  src/finite-group-theory/delooping-sign-homomorphism.lagda.md
  src/finite-group-theory/transpositions-standard-finite-types.lagda.md
  src/foundation-core/commuting-cubes-of-maps.lagda.md
  src/foundation-core/involutions.lagda.md
  src/foundation-core/truncated-types.lagda.md
  src/foundation/coproduct-decompositions.lagda.md
  src/foundation/decidable-equivalence-relations.lagda.md
  src/foundation/relaxed-sigma-decompositions.lagda.md
  src/foundation/sigma-decompositions.lagda.md
  src/foundation/symmetric-identity-types.lagda.md
  src/foundation/trivial-sigma-decompositions.lagda.md
  src/foundation/universal-property-cartesian-product-types.lagda.md
  src/group-theory/normal-submonoids-commutative-monoids.lagda.md
  src/linear-algebra/vectors.lagda.md
  src/lists/permutation-vectors.lagda.md
  src/ring-theory/products-subsets-rings.lagda.md
  src/ring-theory/sums-semirings.lagda.md
  src/species/cauchy-exponentials-species-of-types-in-subuniverses.lagda.md
  src/species/dirichlet-exponentials-species-of-types-in-subuniverses.lagda.md
  src/species/products-dirichlet-series-species-of-types-in-subuniverses.lagda.md
  src/species/small-cauchy-composition-species-of-finite-inhabited-types.lagda.md
  src/species/small-cauchy-composition-species-of-types-in-subuniverses.lagda.md
  src/species/species-of-types-in-subuniverses.lagda.md
  src/structured-types/types-equipped-with-endomorphisms.lagda.md
  src/type-theories/unityped-type-theories.lagda.md
  src/univalent-combinatorics/sigma-decompositions.lagda.md
  src/univalent-combinatorics/type-duality.lagda.md
Labels: CI, pre-commit

#674 Consistently use `python3` everywhere
  .github/workflows/ci.yaml
  .github/workflows/pages.yaml
  .vscode/tasks.json
  CONTRIBUTING.md
  HOWTO-INSTALL.md
  scripts/blank_line_conventions.py
  scripts/demote_foundation_imports.py
  scripts/even_indentation_conventions.py
  scripts/fix_imports.py
  scripts/generate_main_index_file.py
  scripts/generate_namespace_index_modules.py
  scripts/markdown_conventions.py
  scripts/max_line_length_conventions.py
  scripts/remove_unused_imports.py
  scripts/simply_wrappable_long_lines.py
  scripts/spaces_convention.py
  scripts/spaces_conventions_simple.py
  scripts/update_contributors.py
Labels: bug, documentation, CI, tooling

#670 Fix alignment `where` blocks
  CODINGSTYLE.md
  FILE-CONVENTIONS.md
  HOWTO-INSTALL.md
  TEMPLATE.lagda.md
  src/category-theory/discrete-categories.lagda.md
  src/category-theory/slice-precategories.lagda.md
  src/elementary-number-theory/addition-integer-fractions.lagda.md
  src/elementary-number-theory/parity-natural-numbers.lagda.md
  src/elementary-number-theory/powers-of-two.lagda.md
  src/elementary-number-theory/reduced-integer-fractions.lagda.md
  src/elementary-number-theory/type-arithmetic-natural-numbers.lagda.md
  src/elementary-number-theory/universal-property-natural-numbers.lagda.md
  src/foundation/cantor-schroder-bernstein-escardo.lagda.md
  src/foundation/decidable-equivalence-relations.lagda.md
  src/foundation/equivalence-extensionality.lagda.md
  src/foundation/fundamental-theorem-of-identity-types.lagda.md
  src/foundation/perfect-images.lagda.md
  src/foundation/slice.lagda.md
  src/order-theory/galois-connections.lagda.md
  src/orthogonal-factorization-systems/higher-modalities.lagda.md
  src/set-theory/baire-space.lagda.md
  src/set-theory/countable-sets.lagda.md
  src/set-theory/cumulative-hierarchy.lagda.md
  src/univalent-combinatorics/inhabited-finite-types.lagda.md
  src/universal-algebra/algebraic-theory-of-groups.lagda.md
  src/universal-algebra/terms-over-signatures.lagda.md
Labels: cleanup

#676 Remove camelcase from agda-unimath name in titles and logo
  .github/workflows/ci.yaml
  HOME.md
  README.md
  book.toml
  theme/images/README.md
  theme/images/agda-unimath-logo.svg
Labels: website

#677 Fix hyperlinks
  src/orthogonal-factorization-systems/factorization-operations-function-classes.lagda.md
  src/orthogonal-factorization-systems/factorization-operations.lagda.md
  src/orthogonal-factorization-systems/local-types.lagda.md
  src/orthogonal-factorization-systems/pullback-hom.lagda.md
  src/orthogonal-factorization-systems/reflective-modalities.lagda.md
  src/orthogonal-factorization-systems/reflective-subuniverses.lagda.md
  src/orthogonal-factorization-systems/sigma-closed-reflective-modalities.lagda.md
Labels: website, fix
